version: '3'

includes:
  dev: ./scripts/Taskfile.dev.yml
  ci: ./scripts/Taskfile.ci.yml
  docker: ./scripts/Taskfile.docker.yml

vars:
  DOCKER_IMAGE: jeffymathew
  DOCKER_TAG: lite-api

tasks:
  lint:
    cmds:
      - task: ci:install-deps
      - task: dev:tidy
  all:
    desc: Run lint, test, build, and docker-build
    cmds:
      - task: ci:install-deps
      - task: ci:lint
      - task: dev:test
      - task: dev:build
      - task: docker:build