// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./mock/mock.go -package=servicemock
//

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	dto "lite-api/internal/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHotelService is a mock of HotelService interface.
type MockHotelService struct {
	ctrl     *gomock.Controller
	recorder *MockHotelServiceMockRecorder
}

// MockHotelServiceMockRecorder is the mock recorder for MockHotelService.
type MockHotelServiceMockRecorder struct {
	mock *MockHotelService
}

// NewMockHotelService creates a new mock instance.
func NewMockHotelService(ctrl *gomock.Controller) *MockHotelService {
	mock := &MockHotelService{ctrl: ctrl}
	mock.recorder = &MockHotelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHotelService) EXPECT() *MockHotelServiceMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockHotelService) Search(ctx context.Context, request dto.SearchRequest) (dto.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, request)
	ret0, _ := ret[0].(dto.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockHotelServiceMockRecorder) Search(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockHotelService)(nil).Search), ctx, request)
}
