name: Run CI tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci-tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}