name: Deploy to EC2 Auto Scaling Group

on:
  workflow_call:
    secrets:
      ECR_REPOSITORY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      HOTELBEDS_API_KEY:
        required: true
      HOTELBEDS_SECRET:
        required: true
      HOTELBEDS_HOST:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    name: Deploy to EC2 Auto Scaling Group

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update EC2 Instances
        run: |
          echo("to do")
          
